ignoredBuiltDependencies:
  - '@biomejs/biome'

catalogs:
  "shadcn/ui":
    "@radix-ui/react-slot": "^1.2.2"
    "@radix-ui/react-tooltip": "^1.2.6"
    "clsx": "^2.1.1"
    "lucide-react": "^0.507.0"
    "class-variance-authority": "^0.7.1"
    "tailwind-merge": "^3.2.0"
    "tailwindcss-animate": "^1.0.7"
  "core":
    "react": "^18"
    "react-dom": "^18"
    "next": "14.2.25"
    "sharp": "^0.33.4" # next.js 에서 이미지 최적화에 사용하는 라이브러리
  "frontend":
    "react-hook-form": "^7.51.5"
    "react-query": "^3.39.3"
    "next-themes": "^0.3.0"
    "react-notion-x": "^6.16.0"
    "react-icons": "^5.2.1"
  "backend":
    "nodemailer": "^6.9.13"
    "@notionhq/client": "^2.3.0"
  "shared":
    "notion-client": "^6.16.0"
    "github-slugger": "^2.0.0"
    "zod": "^3.24.2"
    "openai": "^5.16.0"
  "monitoring":
    "@vercel/analytics": "^1.3.1"
    "@vercel/speed-insights": "^1.0.12"
  "lint":
    "@biomejs/biome": "2.2.2"
    "eslint": "^8"
    "eslint-config-next": "14.2.2"
  "test":
    "@testing-library/jest-dom": "^6.4.5"
    "@testing-library/react": "^15.0.7"
    "@testing-library/user-event": "^14.5.2"
    "jsdom": "^24.0.0"
    "msw": "^2.3.0"
  "types":
    "@types/node": "^22"
    "@types/nodemailer": "^6.4.15"
    "@types/react": "^18"
    "@types/react-dom": "^18"
    "notion-types": "^6.16.0"
  "build":
    "babel-loader": "^9.1.3"
    "babel-plugin-macros": "^3.1.0"
    "dotenv": "^16.4.5"
    "postcss": "^8"
    "tailwindcss": "^3.4.1"
    "typescript": "^5"
    "vitest": "^1.6.0"
    "@vitejs/plugin-react": "^4.4.1"